steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.', '--network=cloudbuild']

# Docker Push to Artifacts Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$TRIGGER_NAME'
  - '--image'
  - '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
  - '--allow-unauthenticated'
  - '--region'
  - '$_DEPLOY_REGION'
  - '--memory'
  - '$_MEMORY'
  - '--cpu'
  - '$_CPU'
  - '--min-instances'
  - $_MIN_INSTANCES
  - '--max-instances'
  - $_MAX_INSTANCES
  - '--set-env-vars'
  - '$_SET_ENV_VARS'
